// <auto-generated />
using System;
using InterTrips___Turistička_Agencija.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterTrips___Turistička_Agencija.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603082404_IzbrisanEquiredKljuczaSpol")]
    partial class IzbrisanEquiredKljuczaSpol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.AgentPaket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<int>("PaketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaketId");

                    b.HasIndex("AgentId", "PaketId")
                        .IsUnique();

                    b.ToTable("AgentPaket", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Destinacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Kategorija")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SlikaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Destinacija", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Dobavljac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("KontaktOsoba")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VrstaUsluge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dobavljac", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojZvjezdica")
                        .HasColumnType("int");

                    b.Property<int>("DestinacijaId")
                        .HasColumnType("int");

                    b.Property<string>("DostupneUsluge")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DostupnoSoba")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KontaktInformacije")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DestinacijaId");

                    b.ToTable("Hotel", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.KontaktUpit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Poruka")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("Procitano")
                        .HasColumnType("bit");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("KontaktUpit", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Kupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Iskoristen")
                        .HasColumnType("bit");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PopustProcenat")
                        .HasColumnType("int");

                    b.Property<DateTime>("VaziDo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Kupon", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Let", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aviokompanija")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BrojLeta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Odrediste")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Polazak")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SlobodnaSjedista")
                        .HasColumnType("int");

                    b.Property<string>("TipAviona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UkupnoSjedista")
                        .HasColumnType("int");

                    b.Property<DateTime>("VrijemeDolaska")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VrijemePolaska")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Let", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.LogNotifikacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojPokusaja")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumProcitano")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailPrimaoca")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PorukaGreske")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("Procitana")
                        .HasColumnType("bit");

                    b.Property<int?>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipNotifikacije")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("VrijemeSlanja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RezervacijaId");

                    b.ToTable("LogNotifikacija", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Notifikacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Poruka")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Poslano")
                        .HasColumnType("bit");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Notifikacija", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Paket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojPregleda")
                        .HasColumnType("int");

                    b.Property<decimal>("CijenaOd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumPolaska")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPovratka")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinacijaId")
                        .HasColumnType("int");

                    b.Property<int>("DostupniPrevoz")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<int?>("LetId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<double>("Ocjena")
                        .HasColumnType("float");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SlikaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrajanjeNoci")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinacijaId");

                    b.HasIndex("HotelId");

                    b.HasIndex("LetId");

                    b.ToTable("Paket", null, t =>
                        {
                            t.HasTrigger("tr_Paketi_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Placanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Iznos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("KuponId")
                        .HasColumnType("int");

                    b.Property<int>("Metoda")
                        .HasColumnType("int");

                    b.Property<decimal?>("OriginalniIznos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<string>("TransakcijskiKod")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("VrijemePlacanja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KuponId");

                    b.HasIndex("RezervacijaId")
                        .IsUnique();

                    b.ToTable("Placanje", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.PlanPutovanja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RezervacijaId")
                        .IsUnique();

                    b.ToTable("PlanPutovanja", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.PlanPutovanjaTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PaketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaketId");

                    b.ToTable("PlanPutovanjaTemplate", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Putnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojPasosa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Drzavljanstvo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosebniZahtjevi")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipPutnika")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RezervacijaId");

                    b.ToTable("Putnik", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.RataPlacanja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumUplate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUplaceno")
                        .HasColumnType("bit");

                    b.Property<decimal>("IznosRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlacanjeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RokZaUplatu")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlacanjeId");

                    b.ToTable("RatePlacanja");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPolaska")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPovratka")
                        .HasColumnType("datetime2");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PaketId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipPrevoza")
                        .HasColumnType("int");

                    b.Property<string>("TipSobe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("PaketId");

                    b.ToTable("Rezervacija", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.StavkaPlana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Opis")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("PlanPutovanjaId")
                        .HasColumnType("int");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanPutovanjaId");

                    b.ToTable("StavkaPlana", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.StavkaPlanaTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PlanPutovanjaTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Vrijeme")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PlanPutovanjaTemplateId");

                    b.ToTable("StavkaPlanaTemplate", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.TerminPutovanja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPolaska")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPovratka")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<int>("PaketId")
                        .HasColumnType("int");

                    b.Property<int>("Popunjeno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaketId");

                    b.ToTable("TerminPutovanja", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.UslugaPaketa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PaketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaketId");

                    b.ToTable("UslugaPaketa", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1b63ef27-996b-4b13-98db-00f7e4b9bc10",
                            ConcurrencyStamp = "bfd4ec95-77a6-40ae-8904-ddb5a25fd667",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2c74fa38-885b-3b12-87cb-11e8e5c8cd21",
                            ConcurrencyStamp = "5b041b13-1d18-487b-8712-8aab34192ddf",
                            Name = "Agent",
                            NormalizedName = "AGENT"
                        },
                        new
                        {
                            Id = "3d85fb49-774b-2b11-76da-22f9e6d9de32",
                            ConcurrencyStamp = "f7c8760b-fcfc-4517-a9a7-ed6bfc40765a",
                            Name = "Klijent",
                            NormalizedName = "KLIJENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.AgentPaket", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.Korisnik", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterTrips___Turistička_Agencija.Models.Paket", "Paket")
                        .WithMany()
                        .HasForeignKey("PaketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Paket");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Hotel", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.Destinacija", "Destinacija")
                        .WithMany()
                        .HasForeignKey("DestinacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinacija");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.LogNotifikacija", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.Rezervacija", "Rezervacija")
                        .WithMany()
                        .HasForeignKey("RezervacijaId");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Notifikacija", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.ApplicationUser", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Paket", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.Destinacija", "Destinacija")
                        .WithMany("Paketi")
                        .HasForeignKey("DestinacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterTrips___Turistička_Agencija.Models.Hotel", "Hotel")
                        .WithMany("Paketi")
                        .HasForeignKey("HotelId");

                    b.HasOne("InterTrips___Turistička_Agencija.Models.Let", "Let")
                        .WithMany("Paketi")
                        .HasForeignKey("LetId");

                    b.Navigation("Destinacija");

                    b.Navigation("Hotel");

                    b.Navigation("Let");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Placanje", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.Kupon", "Kupon")
                        .WithMany()
                        .HasForeignKey("KuponId");

                    b.HasOne("InterTrips___Turistička_Agencija.Models.Rezervacija", "Rezervacija")
                        .WithOne("Placanje")
                        .HasForeignKey("InterTrips___Turistička_Agencija.Models.Placanje", "RezervacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kupon");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.PlanPutovanja", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.Rezervacija", "Rezervacija")
                        .WithOne("PlanPutovanja")
                        .HasForeignKey("InterTrips___Turistička_Agencija.Models.PlanPutovanja", "RezervacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.PlanPutovanjaTemplate", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.Paket", "Paket")
                        .WithMany()
                        .HasForeignKey("PaketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paket");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Putnik", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.Rezervacija", "Rezervacija")
                        .WithMany("Putnici")
                        .HasForeignKey("RezervacijaId");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.RataPlacanja", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.Placanje", "Placanje")
                        .WithMany("Rate")
                        .HasForeignKey("PlacanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Placanje");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Rezervacija", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.ApplicationUser", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterTrips___Turistička_Agencija.Models.Paket", "Paket")
                        .WithMany("Rezervacije")
                        .HasForeignKey("PaketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Paket");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.StavkaPlana", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.PlanPutovanja", "PlanPutovanja")
                        .WithMany("StavkePlana")
                        .HasForeignKey("PlanPutovanjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPutovanja");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.StavkaPlanaTemplate", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.PlanPutovanjaTemplate", "PlanPutovanjaTemplate")
                        .WithMany("Stavke")
                        .HasForeignKey("PlanPutovanjaTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPutovanjaTemplate");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.TerminPutovanja", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.Paket", "Paket")
                        .WithMany("DostupniTermini")
                        .HasForeignKey("PaketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paket");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.UslugaPaketa", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.Paket", "Paket")
                        .WithMany("Usluge")
                        .HasForeignKey("PaketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paket");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterTrips___Turistička_Agencija.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InterTrips___Turistička_Agencija.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Destinacija", b =>
                {
                    b.Navigation("Paketi");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Hotel", b =>
                {
                    b.Navigation("Paketi");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Let", b =>
                {
                    b.Navigation("Paketi");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Paket", b =>
                {
                    b.Navigation("DostupniTermini");

                    b.Navigation("Rezervacije");

                    b.Navigation("Usluge");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Placanje", b =>
                {
                    b.Navigation("Rate");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.PlanPutovanja", b =>
                {
                    b.Navigation("StavkePlana");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.PlanPutovanjaTemplate", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("InterTrips___Turistička_Agencija.Models.Rezervacija", b =>
                {
                    b.Navigation("Placanje");

                    b.Navigation("PlanPutovanja");

                    b.Navigation("Putnici");
                });
#pragma warning restore 612, 618
        }
    }
}
